INSERT INTO Book_List (author, title )
VALUES ('John Steinbeck', 'Of Mice and Men'),
('Stephen King', 'Carrie'),
('John Steinbeck', 'The Grapes of Wrath'),
('John Grisham', 'The Firm'),
('Edgar Allan Poe', 'The Black Cat'),
('William Faulkner', 'The Sound and the Fury'),
('F. Scott Fitzgerald', 'The Great Gatsby'),
('Edgar Allan Poe', 'The Fall of the House of Usher'),
('Mark Twain', 'The Adventure of Tom Sawyer'),
('Mark Twain', 'Adventures of Huckleberry Finn'),
('O. Henry', 'The Four Million'),
('Ernest Hemingway', 'The Old Man and the Sea'),
('Harper Lee', 'To Kill a Mockingbird'),
('F. Scott Fitzgerald', 'The Catcher in the Rye'),
('Toni Morrison', 'Beloved'),
('John Steinbeck', 'East of Eden'),
('Ray Bradbury', 'Fahrenheit 451'), 
('Stephen King', 'The Shining'), 
('J.D. Salinger', 'Nine Stories'),
('Kurt Vonnegut', 'Slaughterhouse-Five'),
('Harper Lee', 'Go Set a Watchman'),
('Ernest Hemingway', 'For Whom the Bell Tolls'),
('Kurt Vonnegut', 'Cat''s Cradle'),
('Maya Angelou', 'I Know Why the Caged Bird Sings'), 
('John Steinbeck', 'Cannery Row'),
('Jack Kerouac', 'On the Road'),
('Ernest Hemingway', 'The Sun Also Rises'),
('Maya Angelou', 'The Heart of a Woman'),
('Kurt Vonnegut', 'Breakfast of Champions'),
('Ray Bradbury', 'The Martian Chronicles'),
('Stephen King', 'It'), 
('Toni Morrison', 'The Bluest Eye');


INSERT INTO BOOK_CATEGORY (category, book_list_id )
VALUES ('Tragedy', 1),
('Horror', 2),
('Classic', 3),
('Thriller', 4),
('Horror', 5),
('Modernist Novel', 6),
('Tragedy', 7),
('Horror', 8),
('Children''s literature', 9),
('Children''s literature', 10),
('Short Stories', 11),
('Literary fiction', 12),
('Southern  Gothic', 13),
('Realistic Fiction', 14),
('N/A', 15),
('N/A', 16),
('N/A', 17),
('Dyostopian', 18),
('Short Stories', 19),
('Dark comedy', 20),
('N/A', 21),
('War novel', 22),
('Science Fiction', 23),
('Autobiography', 24),
('Regional slice of life', 25),
('Stream of Consciousness', 26),
('Horror', 27),
('Autobiography', 28),
('Metafiction', 29),
('Science Fiction', 30),
('Horror', 31),
('African-American-Literature', 32);
